project_name: weigh

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - id: weigh
    dir: cmd/weigh
    binary: weigh
    env:
      - CGO_ENABLED=0
    goarm:
      - 6
      - 7
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.appName={{.Binary}}
    ignore:
      - goos: freebsd
        goarch: arm

archives:
  - replacements:
      freebsd: FreeBSD
      linux: Linux
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
# Already using git-chglog
changelog:
  skip: true

dockers:
  - dockerfile: build/package/Dockerfile
    image_templates:
      - 'zachfi/weigh:{{ .Tag }}'
      - 'zachfi/weigh:v{{ .Major }}.{{ .Minor }}'
      - 'zachfi/weigh:latest'
    build_flag_templates:
      - '--pull'
      - '--label=repository=https://github.com/zachfi/weigh'

release:
  name_template: '{{.ProjectName}} v{{.Version}}'
