version: 2

project_name: weigh

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - id: weigh
    dir: cmd/weigh
    binary: weigh
    env:
      - CGO_ENABLED=0
    goarm:
      - 6
      - 7
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.appName={{.Binary}}
    ignore:
      - goos: freebsd
        goarch: arm

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "linux" }}Linux
      {{- else if eq .Os "freebsd" }}FreeBSD
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm" }}arm{{ .ArmVersion }}
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  version_template: '{{ .Tag }}-next'

# Already using git-chglog
changelog:
  disable: true

dockers:
  - dockerfile: build/package/Dockerfile
    image_templates:
      - 'zachfi/weigh:{{ .Tag }}'
      - 'zachfi/weigh:v{{ .Major }}.{{ .Minor }}'
      - 'zachfi/weigh:latest'
    build_flag_templates:
      - '--pull'
      - '--label=repository=https://github.com/zachfi/weigh'

release:
  name_template: '{{.ProjectName}} v{{.Version}}'
